### ISSUE TITLE
Insane lag when editing Fennel in Markdown code blocks

### ISSUE THREAD

**Issue by enderger** [Olical/aniseed#53] opened 2021-07-06 16:18 UTC
For some reason, editing Fennel embedded in a Markdown code block produces large amounts of lag.
![lag-example](https://user-images.githubusercontent.com/36283171/124634038-bcaf3300-de3a-11eb-9e08-96394765fd97.gif)
I don't quite know what causes this, but I can say that it gets worse quickly.

**Comment by Olical** [comment] 2021-07-07 08:45
Hey there, would you be able to elaborate a bit here? I can't reproduce this at all.

Conjure doesn't run or even load in markdown files, so I presume you're using some plugin to embed filetypes within other filetypes (through TreeSitter?) and I guess that's having some weird interaction with Conjure.

I would guess your autocomplete is running, failing and consuming a lot of CPU, but that's a wild guess. Any plugins you're using to do this would be useful for reproduction. Thanks!

**Comment by Olical** [comment] 2021-07-07 08:46
If you could try turning off Conjure's completion etc (see the :help files) and see if the problem goes away, that'd be really good! And if you're using tree sitter, you can enable the experimental treesitter form extraction code, again, in `:help conjure` if you have a grep for treesitter.

**Comment by Olical** [comment] 2021-07-07 08:46
Oh I assumed this was Conjure, if you're only using Aniseed then I don't see how this would make a difference, Aniseed has no interactive components whatsoever, so I doubt it's Aniseed at all in that case.

**Comment by enderger** [comment] 2021-07-07 13:55
Unfortunately,  disabling Aniseed appears to fix the problem, as does switching into Clojure mode. I presume that Aniseed tries to load something more than just syntax highlighting when embedded in Markdown, causing lag on failure.

**Comment by Olical** [comment] 2021-07-10 12:48
I can't reproduce this at all though, if I have a code block in markdown it's just unhighlighted code, so I presume you have a plugin to enable sub-language support in buffers? That leans on TreeSitter somehow?

I'm afraid I won't be able to reproduce this until I can reproduce the exact setup you're using. I would imagine it's to do with how your language-in-language thing is implemented but I can't be sure.

Maybe disabling omnicompletion support will help?

```vim
let g:conjure#completion#omnifunc = v:null
```

**Comment by enderger** [comment] 2021-07-11 23:20
Ok, forgot I had Polyglot providing Markdown support. If [vim-markdown](https://github.com/plasticboy/vim-markdown) is installed and the following is set, the issue should occur.
```fennel
(set nvim.g.markdown_fenced_languages  [ "fennel" ])
```

**Comment by Olical** [comment] 2021-07-18 13:46
Hmm, huge guess but is this issue related perhaps? https://github.com/plasticboy/vim-markdown/issues/162 they mention setting `let g:vim_markdown_folding_disabled = 1` (presumably at startup before you enter the markdown buffer)

Does that magically fix the issue?

**Comment by enderger** [comment] 2021-07-18 18:15
Unfortunately not.

**Comment by Olical** [comment] 2021-08-13 12:46
I think this is related to the mentioned Conjure issue, it's really something to do with `readline` being installed alongside `fennel` and running the REPL in a headless environment. I'm not sure why, but I've set the recommended `TERM=dumb` environment variable on the `develop` branch of Conjure now.

Updating to that _should_ fix your problem since it seems like you were running into the exact same thing. If this is no longer an issue for you due to it being fixed or not using the tooling any more please feel free to close it. Thanks!

**Comment by Olical** [comment] 2021-08-21 10:41
I'm going to close this assuming that my recent work fixed it and it wasn't to do with markdown, but readline slowing things down for some unknown reason.

**Closed by Olical** 2021-08-21 10:41 UTC
Labels: bug
